#!/usr/bin/env python3
"""Generates Backend/GameData/cs2_game_data.h from CS2 dump JSONs.

Usage: python tools/gen_game_data.py
Reads: vtables.json, entities.json, gameevents.json, protobufs.json, patterns (4).json
"""
import json
import os
import re
import datetime

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(PROJECT_ROOT, "Backend", "GameData", "cs2_game_data.h")
OFFSETS_H = os.path.join(PROJECT_ROOT, "cs2", "offsets.h")

SOURCES = {
    "vtables": r"C:\Users\Kacper\Downloads\vtables.json",
    "entities": r"C:\Users\Kacper\Downloads\entities.json",
    "gameevents": r"C:\Users\Kacper\Downloads\gameevents.json",
    "protobufs": r"C:\Users\Kacper\Downloads\protobufs.json",
    "patterns": r"C:\Users\Kacper\Downloads\patterns (4).json",
}


def cstr(s):
    if s is None:
        return "nullptr"
    esc = str(s).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{esc}"'


def ident(s):
    s = re.sub(r"[^A-Za-z0-9_]", "_", str(s))
    if not s or s[0].isdigit():
        s = "_" + s
    return s


def flit(x):
    return f"{float(x):.6f}f"


def s32(v):
    """JSON u32 sentinel (0xFFFFFFFF) -> signed."""
    v = int(v)
    return v - 0x100000000 if v >= 0x80000000 else v


def load(name):
    with open(SOURCES[name], "r", encoding="utf-8") as f:
        return json.load(f)


def load_patterns():
    """patterns (4).json is JSON5-ish: contains 0x-prefixed hex numbers. Sanitize first."""
    with open(SOURCES["patterns"], "r", encoding="utf-8") as f:
        text = f.read()
    text = re.sub(
        r'("(?:va|rva)"\s*:\s*)0x([0-9A-Fa-f]+)',
        lambda m: f'{m.group(1)}{int(m.group(2), 16)}',
        text)
    return json.loads(text)


PROTO_TYPE_NAMES = {
    1: "double", 2: "float", 3: "int64", 4: "uint64", 5: "int32",
    6: "fixed64", 7: "fixed32", 8: "bool", 9: "string", 10: "group",
    11: "message", 12: "bytes", 13: "uint32", 14: "enum",
    15: "sfixed32", 16: "sfixed64", 17: "sint32", 18: "sint64",
}


def cross_check_signatures(patterns):
    """Compare offsets.h hand-curated signatures against the dump. Prints a report."""
    try:
        with open(OFFSETS_H, "r", encoding="utf-8") as f:
            text = f.read()
    except OSError as e:
        print(f"  (skipping cross-check, can't read offsets.h: {e})")
        return
    sigs = re.findall(r'constexpr const char\*\s+(\w+)\s*=\s*"([^"]+)"', text)
    by_pattern = {}
    for p in patterns:
        pat = (p.get("pattern") or "").strip()
        if pat:
            by_pattern.setdefault(pat, []).append(p)
    exact = 0
    print("  Cross-check offsets.h signatures vs patterns dump:")
    for name, pat in sigs:
        hits = by_pattern.get(pat)
        if hits:
            h = hits[0]
            print(f"    [exact] {name:28s} -> {h['name']} ({h['module']}, rva 0x{h.get('rva', 0):X})")
            exact += 1
        else:
            print(f"    [miss ] {name}")
    print(f"    {exact}/{len(sigs)} signatures found verbatim in dump")


def main():
    vt = load("vtables")
    en = load("entities")
    ev = load("gameevents")
    pb = load("protobufs")
    pt = load_patterns()

    o = []
    w = o.append

    w("// cs2_game_data.h -- generated by tools/gen_game_data.py, do not edit by hand.")
    w(f"// Generated: {datetime.datetime.now().isoformat(timespec='seconds')}")
    w(f"// Sources: vtables.json, entities.json, gameevents.json, protobufs.json, patterns (4).json "
      f"(CS2 build {en.get('build_number', '?')}, {pt.get('found', '?')} patterns)")
    w("#pragma once")
    w("")
    w("#include <cstdint>")
    w("#include <cstring>")
    w("")
    w("namespace game_data {")
    w("")
    w("// ------------------------------------------------------------------")
    w("// Vtables")
    w("// ------------------------------------------------------------------")
    w("struct VtableMethod {")
    w("    int index;")
    w("    const char* name;   // nullptr when unnamed")
    w("    uint32_t rva;")
    w("};")
    w("")
    w("struct VtableInterface {")
    w("    const char* interface_name;")
    w("    const char* rtti_class;")
    w("    uint32_t vtable_rva;")
    w("    const VtableMethod* methods;")
    w("    int method_count;")
    w("};")
    w("")
    w("struct VtableModule {")
    w("    const char* module_name;")
    w("    const VtableInterface* interfaces;")
    w("    int interface_count;")
    w("};")
    w("")

    modules = vt.get("modules", {})
    for mod_name in sorted(modules):
        mod_id = ident(mod_name)
        ifaces = modules[mod_name]
        iface_entries = []
        for if_name in sorted(ifaces):
            if_id = ident(if_name)
            data = ifaces[if_name]
            methods = data.get("methods", [])
            arr = f"k_{mod_id}_{if_id}_methods"
            w(f"inline constexpr VtableMethod {arr}[] = {{")
            for m in methods:
                w(f"    {{{m.get('index', 0)}, {cstr(m.get('name'))}, "
                  f"{int(m.get('rva', 0))}u}},")
            w("};")
            w("")
            iface_entries.append(
                (if_name, data.get("rtti_class"), int(data.get("vtable_rva", 0)),
                 arr, len(methods)))
        w(f"inline constexpr VtableInterface k_{mod_id}_interfaces[] = {{")
        for (if_name, rtti, vrva, arr, cnt) in iface_entries:
            w(f"    {{{cstr(if_name)}, {cstr(rtti)}, {vrva}u, {arr}, {cnt}}},")
        w("};")
        w("")

    w("inline constexpr VtableModule k_vtable_modules[] = {")
    for mod_name in sorted(modules):
        mod_id = ident(mod_name)
        cnt = len(modules[mod_name])
        w(f"    {{{cstr(mod_name)}, k_{mod_id}_interfaces, {cnt}}},")
    w("};")
    w(f"inline constexpr int k_vtable_modules_count = {len(modules)};")
    w("")

    w("// ------------------------------------------------------------------")
    w(f"// Game events (CS2 build {en.get('build_number', '?')})")
    w("// ------------------------------------------------------------------")
    w("struct EventField {")
    w("    const char* name;")
    w("    const char* type;")
    w("};")
    w("")
    w("struct GameEvent {")
    w("    const char* name;")
    w("    uint32_t id;")
    w("    bool local;")
    w("    const EventField* fields;")
    w("    int field_count;")
    w("};")
    w("")

    for i, e in enumerate(ev.get("events", [])):
        fields = e.get("fields", [])
        if fields:
            arr = f"k_event_{i:03d}_fields"
            w(f"inline constexpr EventField {arr}[] = {{")
            for fld in fields:
                w(f"    {{{cstr(fld.get('name'))}, {cstr(fld.get('type'))}}},")
            w("};")
            w("")
    w("inline constexpr GameEvent k_game_events[] = {")
    for i, e in enumerate(ev.get("events", [])):
        fields = e.get("fields", [])
        arr = f"k_event_{i:03d}_fields" if fields else "nullptr"
        eid = int(e.get("id", 0)) & 0xFFFFFFFF
        w(f"    {{{cstr(e.get('name'))}, {eid}u, "
          f"{'true' if e.get('local') else 'false'}, {arr}, {len(fields)}}},")
    w("};")
    w(f"inline constexpr int k_game_events_count = {len(ev.get('events', []))};")
    w("")

    w("// ------------------------------------------------------------------")
    w(f"// Entity snapshot (CS2 build {en.get('build_number', '?')})")
    w("// ------------------------------------------------------------------")
    w("struct EntityClass {")
    w("    const char* classname;")
    w("    int count;")
    w("};")
    w("")
    w("struct EntitySnapshot {")
    w("    const char* classname;")
    w("    int index;")
    w("    int health;")
    w("    int max_health;")
    w("    float origin[3];")
    w("    int team;")
    w("};")
    w("")
    w(f"inline constexpr int k_build_number = {int(en.get('build_number', 0))};")
    w("inline constexpr EntityClass k_entity_classes[] = {")
    for c in en.get("by_class", []):
        w(f"    {{{cstr(c.get('classname'))}, {int(c.get('count', 0))}}},")
    w("};")
    w("")
    w("inline constexpr EntitySnapshot k_entity_snapshot[] = {")
    for ent in en.get("entities", []):
        org = (list(ent.get("origin", [0, 0, 0])) + [0, 0, 0])[:3]
        w(f"    {{{cstr(ent.get('classname'))}, {int(ent.get('index', 0))}, "
          f"{int(ent.get('health', 0))}, {int(ent.get('max_health', 0))}, "
          f"{{{flit(org[0])}, {flit(org[1])}, {flit(org[2])}}}, "
          f"{int(ent.get('team', 0))}}},")
    w("};")
    w(f"inline constexpr int k_entity_classes_count = {len(en.get('by_class', []))};")
    w(f"inline constexpr int k_entity_snapshot_count = {len(en.get('entities', []))};")
    w("")

    w("// ------------------------------------------------------------------")
    w("// Protobuf message layouts (in-memory, per module)")
    w("// ------------------------------------------------------------------")
    w("// type: protobuf wire type (see proto_type_name), label: 1=optional 2=required 3=repeated,")
    w("// has_bit: index in the has-bits word (-1 = none), offset/has_bits_offset in bytes (-1 = n/a).")
    w("struct ProtoField {")
    w("    const char* name;")
    w("    int32_t offset;      // -1 when the field has no static offset")
    w("    int number;")
    w("    int32_t has_bit;     // -1 when none")
    w("    uint32_t type;")
    w("    uint32_t label;")
    w("};")
    w("")
    w("struct ProtoMessage {")
    w("    const char* name;")
    w("    int32_t size;")
    w("    int32_t has_bits_offset;  // -1 when none")
    w("    const ProtoField* fields;")
    w("    int field_count;")
    w("};")
    w("")
    w("struct ProtoModule {")
    w("    const char* module_name;")
    w("    const ProtoMessage* messages;")
    w("    int message_count;")
    w("};")
    w("")

    for mod_name in sorted(pb):
        mod_id = ident(mod_name)
        msgs = pb[mod_name]
        msg_entries = []
        for msg_name in sorted(msgs):
            msg_id = ident(msg_name)
            data = msgs[msg_name]
            fields = data.get("fields", {})
            arr = f"k_proto_{mod_id}_{msg_id}_fields"
            w(f"inline constexpr ProtoField {arr}[] = {{")
            if not fields:
                # zero-sized arrays are ill-formed in C++; a dummy entry keeps field_count == 0
                w("    {nullptr, -1, 0, -1, 0u, 0u},")
            for fname in sorted(fields, key=lambda f: int(fields[f].get("number", 0))):
                fld = fields[fname]
                w(f"    {{{cstr(fname)}, {s32(fld.get('offset', -1))}, "
                  f"{int(fld.get('number', 0))}, {s32(fld.get('has_bit', -1))}, "
                  f"{int(fld.get('type', 0))}u, {int(fld.get('label', 0))}u}},")
            w("};")
            w("")
            msg_entries.append((msg_name, s32(data.get("size", -1)),
                                s32(data.get("has_bits_offset", -1)), arr, len(fields)))
        w(f"inline constexpr ProtoMessage k_proto_{mod_id}_messages[] = {{")
        for (msg_name, size, hbo, arr, cnt) in msg_entries:
            w(f"    {{{cstr(msg_name)}, {size}, {hbo}, {arr}, {cnt}}},")
        w("};")
        w("")

    w("inline constexpr ProtoModule k_proto_modules[] = {")
    for mod_name in sorted(pb):
        mod_id = ident(mod_name)
        cnt = len(pb[mod_name])
        w(f"    {{{cstr(mod_name)}, k_proto_{mod_id}_messages, {cnt}}},")
    w("};")
    w(f"inline constexpr int k_proto_modules_count = {len(pb)};")
    w("")

    w("// ------------------------------------------------------------------")
    w(f"// Resolved signature patterns ({pt.get('found', '?')} found, {pt.get('missing', '?')} missing)")
    w("// ------------------------------------------------------------------")
    w("// resolve: raw = pattern hits the target, riprel = rip-relative lea target, rel32 = call target")
    w("struct PatternEntry {")
    w("    const char* name;")
    w("    const char* module;")
    w("    const char* resolve;")
    w("    const char* pattern;")
    w("    const char* prototype;")
    w("    uint32_t rva;")
    w("};")
    w("")
    w("inline constexpr PatternEntry k_patterns[] = {")
    for i, p in enumerate(pt.get("patterns", [])):
        name = p.get("name")
        arr_safe = ident(name)
        # duplicate names exist; disambiguate via generated comment + linear scan (first hit wins)
        _ = arr_safe  # (kept for readability only)
        w(f"    {{{cstr(name)}, {cstr(p.get('module'))}, {cstr(p.get('resolve'))}, "
          f"{cstr(p.get('pattern'))}, {cstr(p.get('prototype'))}, {int(p.get('rva', 0))}u}}, "
          f"// #{i}")
    w("};")
    w(f"inline constexpr int k_patterns_count = {pt.get('found', len(pt.get('patterns', [])))};")
    w("")

    w("// ------------------------------------------------------------------")
    w("// Lookup helpers")
    w("// ------------------------------------------------------------------")
    w("inline const VtableModule* find_module(const char* module_name) {")
    w("    if (!module_name)")
    w("        return nullptr;")
    w("    for (int i = 0; i < k_vtable_modules_count; ++i)")
    w("        if (std::strcmp(k_vtable_modules[i].module_name, module_name) == 0)")
    w("            return &k_vtable_modules[i];")
    w("    return nullptr;")
    w("}")
    w("")
    w("inline const VtableInterface* find_interface(const char* module_name, const char* interface_name) {")
    w("    const VtableModule* mod = find_module(module_name);")
    w("    if (!mod || !interface_name)")
    w("        return nullptr;")
    w("    for (int i = 0; i < mod->interface_count; ++i)")
    w("        if (std::strcmp(mod->interfaces[i].interface_name, interface_name) == 0)")
    w("            return &mod->interfaces[i];")
    w("    return nullptr;")
    w("}")
    w("")
    w("inline const GameEvent* find_event(const char* event_name) {")
    w("    if (!event_name)")
    w("        return nullptr;")
    w("    for (int i = 0; i < k_game_events_count; ++i)")
    w("        if (std::strcmp(k_game_events[i].name, event_name) == 0)")
    w("            return &k_game_events[i];")
    w("    return nullptr;")
    w("}")
    w("")
    w("inline const GameEvent* find_event_by_id(uint32_t event_id) {")
    w("    for (int i = 0; i < k_game_events_count; ++i)")
    w("        if (k_game_events[i].id == event_id)")
    w("            return &k_game_events[i];")
    w("    return nullptr;")
    w("}")
    w("")
    w("inline const ProtoModule* find_proto_module(const char* module_name) {")
    w("    if (!module_name)")
    w("        return nullptr;")
    w("    for (int i = 0; i < k_proto_modules_count; ++i)")
    w("        if (std::strcmp(k_proto_modules[i].module_name, module_name) == 0)")
    w("            return &k_proto_modules[i];")
    w("    return nullptr;")
    w("}")
    w("")
    w("inline const ProtoMessage* find_proto_message(const char* module_name, const char* message_name) {")
    w("    const ProtoModule* mod = find_proto_module(module_name);")
    w("    if (!mod || !message_name)")
    w("        return nullptr;")
    w("    for (int i = 0; i < mod->message_count; ++i)")
    w("        if (std::strcmp(mod->messages[i].name, message_name) == 0)")
    w("            return &mod->messages[i];")
    w("    return nullptr;")
    w("}")
    w("")
    w("inline const ProtoField* find_proto_field(const char* module_name, const char* message_name, const char* field_name) {")
    w("    const ProtoMessage* msg = find_proto_message(module_name, message_name);")
    w("    if (!msg || !field_name)")
    w("        return nullptr;")
    w("    for (int i = 0; i < msg->field_count; ++i)")
    w("        if (std::strcmp(msg->fields[i].name, field_name) == 0)")
    w("            return &msg->fields[i];")
    w("    return nullptr;")
    w("}")
    w("")
    w("inline const PatternEntry* find_pattern(const char* name) {")
    w("    if (!name)")
    w("        return nullptr;")
    w("    for (int i = 0; i < k_patterns_count; ++i)")
    w("        if (std::strcmp(k_patterns[i].name, name) == 0)")
    w("            return &k_patterns[i];")
    w("    return nullptr;")
    w("}")
    w("")
    w("inline const PatternEntry* find_pattern(const char* module_name, const char* name) {")
    w("    if (!module_name || !name)")
    w("        return nullptr;")
    w("    for (int i = 0; i < k_patterns_count; ++i)")
    w("        if (std::strcmp(k_patterns[i].name, name) == 0 &&")
    w("            std::strcmp(k_patterns[i].module, module_name) == 0)")
    w("            return &k_patterns[i];")
    w("    return nullptr;")
    w("}")
    w("")
    w("inline const char* proto_type_name(uint32_t wire_type) {")
    w("    switch (wire_type) {")
    for t, n in sorted(PROTO_TYPE_NAMES.items()):
        w(f"    case {t}u: return \"{n}\";")
    w("    default: return \"unknown\";")
    w("    }")
    w("}")
    w("")
    w("} // namespace game_data")
    w("")

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(o))

    n_methods = sum(len(d.get("methods", [])) for m in modules.values() for d in m.values())
    n_msgs = sum(len(m) for m in pb.values())
    n_fields = sum(len(d.get("fields", {})) for m in pb.values() for d in m.values())
    print(f"Wrote {OUT_PATH}")
    print(f"  vtables : {len(modules)} modules, {sum(len(m) for m in modules.values())} interfaces, {n_methods} methods")
    print(f"  events  : {len(ev.get('events', []))}")
    print(f"  entities: {len(en.get('by_class', []))} classes, {len(en.get('entities', []))} snapshot entries")
    print(f"  protobuf: {len(pb)} modules, {n_msgs} messages, {n_fields} fields")
    print(f"  patterns: {pt.get('found', '?')} resolved, {pt.get('missing', '?')} missing")
    cross_check_signatures(pt.get("patterns", []))


if __name__ == "__main__":
    main()
